import os, sys, getopt
import pickle
import numpy as np
import pandas as pd
import muon
from tqdm import tqdm
from seq2exp_functions import split_genes_kf
import time

'''
Required Inputs
---------------
    -i (input directory)
        the directory containing the ATAC and RNA H5AD files
    -c (cell type code string)
        cell type id(s) to select (can be an int or ints separated by commas; eg.: 1,2,3); { 0: 'B cell', 1: 'CD14+ monocyte', 2: 'CD4 T cell', 3: 'CD8 T cell', 4: 'other', 5: 'astrocyte/microglia', 6: 'oligodendrocyte', 7: 'neuron', 8: 'OPC', 9: 'epithelial', 10: 'stromal (immune)', 11: 'stromal (other)', 12: 'ISC' }
    -s (int)
        promoter sequence start position, relative to the TSS (should be between -1000 and 500); default is -500
    -e (int)
        promoter sequence end position, relative to the TSS (should be between -500 and 1000); default is 0
    -a (ATAC seq data)
        normalized ATAC-seq signal (fragments) for the chosen cell type (pooled from all cells) ==> generated by pool_atac_fragments_by_gene.py
    -o (output directory)
        the directory where the output should be written (should already exist)
    -l (full path)
        path to the promoter locs file
    -p (full path)
        path to the promoter seqs file
'''

def main(argv):
    try:
        opts, _ = getopt.getopt(argv, 'i:o:c:s:e:a:l:p:')
    except getopt.GetoptError:
        print('\n::: Error: cannot parse command line inputs')
        sys.exit(2) 
    for opt, arg in opts:
        if opt == '-i':
            global input_dir
            input_dir = arg
        elif opt == '-c':
            global cell_types_command
            cell_types_command = arg
        elif opt == '-s':
            global seq_start
            seq_start = int(arg)
        elif opt == '-e':
            global seq_end
            seq_end = int(arg)
        elif opt == '-o':
            global output_dir
            output_dir = arg
        elif opt == '-a':
            global atac_file
            atac_file = arg
        elif opt == '-l':
            global locs_file
            locs_file = arg
        elif opt == '-p':
            global seqs_file
            seqs_file = arg


if __name__ == "__main__":

    # default values
    n_folds = 5
    seq_start = -1000
    seq_end = 1000

    # read command line arguments
    main(sys.argv[1:])

    # parse cell types
    if cell_types_command == None:
        print('\n::: Error: no cell type id given')
        sys.exit(2)
    else:
        if len(cell_types_command) == 1:
            cell_types = int(cell_types_command)
            print('\n::: Interpreted cell type: {}'.format(cell_types))
        else:
            tokens = cell_types_command.split(',')
            cell_types = []
            for t in tokens:
                if t.isnumeric():
                    t_int = int(t)
                    if t_int not in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]:
                        print('\n::: Error: cell type id does not exist ({})'.format(t_int))
                        sys.exit(2)
                    else:
                        cell_types.append(t_int)
                else:
                    print('\n::: Error: cannot parse cell type ids given, use ints separated only by commas')
                    sys.exit(2)
            print('\n::: Interpreted cell types: {}'.format(', '.join(tokens)))

    # check if the sequence coordinates are ok
    if seq_start < -1000 or seq_start > 500:
        print('\n::: Error: promoter sequence should start between -1000 and 500')
        sys.exit(2)
    if seq_end < -500 or seq_end > 1000:
        print('\n::: Error: promoter sequence should end between -500 and 1000')
        sys.exit(2)
    
    # convert TSS-relative positions to sequence indices
    start_pos = seq_start + 1000
    end_pos = seq_end + 1000
    seq_len = end_pos - start_pos

    # read multiome data
    time1 = time.time()
    h5_file = [ file for file in os.listdir(input_dir) if 'filtered_feature_bc_matrix.h5' in file ][0]
    mdata = muon.read_10x_h5(input_dir + '/' + h5_file)
    # atac_raw = mdata.mod['atac']
    rna_raw = mdata.mod['rna']
    del mdata
    # atac_arr = atac_raw.X.toarray()
    rna_arr = rna_raw.X.toarray()
    time2 = time.time()
    print('Read data in %.2f seconds' % (time2 - time1))

    # prepare peaks
    with open(atac_file, 'rb') as f:
        atac_dict = pickle.load(f)

    # read cell type annotations and map them to anndata indices
    cell_type_annotations = pd.read_csv(os.path.join(input_dir, 'cell_type_annotations.csv'), index_col = 0)
    cells_in_data = rna_raw.obs_names
    all_cell_types = []
    for cell in cells_in_data:
        if cell in cell_type_annotations.index:
            all_cell_types.append(cell_type_annotations.loc[cell].cell_type)
        else:
            all_cell_types.append('none')

    # generate list of indices for cells
    cell_type_dict = { 'B cell': 0, 'CD14+ monocyte': 1, 'CD4 T cell': 2, 'CD8 T cell': 3, 'other': 4, 'astrocyte/microglia': 5, 'oligodendrocyte': 6, 'neuron': 7, 'OPC': 8, 'none': -100, 'epithelial': 9, 'stromal (immune)': 10, 'stromal (other)': 11, 'ISC': 12 }
    all_cell_codes = np.array([ cell_type_dict[i] for i in all_cell_types ])

    # select cells
    if type(cell_types) == int:
        selected_cell_indices = np.where(all_cell_codes == cell_types)[0]
        cell_types_str = str(cell_types)
    else:
        cell_arrays = []
        for i in cell_types:
            cell_arrays.append(np.where(all_cell_codes == i)[0])
        selected_cell_indices = np.concatenate(cell_arrays)
        cell_types_str = '-'.join([ str(i) for i in sorted(cell_types) ])

    # subset the atac and rna arrays to the selected cells
    cell_rna_arr = rna_arr[selected_cell_indices, :]
    n_cells = selected_cell_indices.shape[0]

    # pool signals from selected cells
    pooled_rna_arr = np.sum(np.where(cell_rna_arr > 0, 1, 0), axis = 0)

    # read promoter info
    time1 = time.time()
    with open(locs_file, 'rb') as f:
        promoter_dict = pickle.load(f)
    promoter_seqs = np.load(seqs_file)
    all_genes = np.array(sorted(list(promoter_seqs.files)))
    time2 = time.time()
    print('Read promoter data in %.2f seconds' % (time2 - time1))

    # get the cells and genes
    time1 = time.time()
    train_genes, test_genes = split_genes_kf(n_folds, all_genes)
    time2 = time.time()
    print('Split train and test data in %.2f seconds' % (time2 - time1))
    
    # make a directory for the data
    subdir = output_dir + '/pooled_{}to{}_{}'.format(seq_start, seq_end, cell_types_str)
    os.mkdir(subdir)

    # iterate over folds to get data for each gene
    for fold in tqdm(range(n_folds), total = n_folds):

        # get data for train and test indices
        for t, samples in enumerate([train_genes, test_genes]):

            time1 = time.time()
            s = len(samples[fold])

            # takes ~5 min to run for 100,000 samples
            atac_signals = np.zeros((s, seq_len), dtype = float)
            sample_seqs = np.zeros((s, seq_len), dtype = int)
            rna_signals = np.zeros(s, dtype = float)

            for i in range(s):

                gene = samples[fold][i]

                # get the atac signal
                if gene in atac_dict.keys():
                    atac_signal = atac_dict[gene][start_pos:end_pos]
                else:
                    atac_signal = np.zeros(seq_len)

                # get the rna signal
                if gene in rna_raw.var.gene_ids.values:
                    rna_signal = pooled_rna_arr[rna_raw.var.gene_ids == gene][0] / n_cells
                else:
                    rna_signal = 0.0

                atac_signals[i] = atac_signal
                sample_seqs[i] = promoter_seqs[gene][start_pos:end_pos]
                rna_signals[i] = rna_signal

            time2 = time.time()
            print('Collected samples in %.2f seconds' % (time2 - time1))

            time1 = time.time()
            data_dict = { 'samples': np.array(samples[fold]), 'atac': atac_signals, 'sequence': sample_seqs, 'rna': rna_signals }
            np.savez(subdir + '/{}_{}.npz'.format(['train', 'test'][t], fold), **data_dict)
            time2 = time.time()
            print('Wrote data to file in %.2f seconds' % (time2 - time1))

    print('\n::: Wrote datasets for CV to {}'.format(output_dir))
    print('. . . . . . . . . . . . . . . . . . . . . . . . . . . . .')